# Pengguna extensi REST Client di Visual Studio Code untuk melakukan testing
# kalau URI-nya beda bisa menyesuaikan (menganti @BASE_URI)

@BASE_URI = 127.0.0.1:8000

### Ambil semua todo
GET http://{{BASE_URI}}/todo HTTP/1.1
Accept: application/json

### Membuat todo 1
POST http://{{BASE_URI}}/todo HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "judul": "Todo post pertama ku!"
}

### Membuat todo 2
POST http://{{BASE_URI}}/todo HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "judul": "Todo post kedua ku!"
}

### Menghapus todo 1
DELETE http://{{BASE_URI}}/todo/delete.php?id=1 HTTP/1.1
Accept: application/json

### Menandai todo 2 selesai
PATCH http://{{BASE_URI}}/todo/complete.php?id=2 HTTP/1.1
Accept: application/json